### ISSUE TITLE
Create face recognition endpoint and worker

### ISSUE THREAD

**Issue by SpringHawk** [codeuniversity/smag-mvp#136]
- read internal_image_url, post_id and boundries from kafka topic
- call face recognition GRPC endpoint with image url
- take internal_image_url and boundries to crop image, creating image_crop_url for image proxy
- write array of faces with boundries and encoding to kafka topic

**Comment by alexmorten** [comment]
`imgproxy` to crop the images: https://github.com/imgproxy/imgproxy
