### ISSUE TITLE
Unify naming conventions in project

### ISSUE THREAD

**Issue by m-lukas** [codeuniversity/smag-mvp#22]
## Make sure we keep with the namings:
- `<platform>_scraper`
- `<platform>_<database>-inserter`

## We should unify it all over the place:
- file structure
- variable-, function-names
- docker, docker-hub
- kubernetes
- circle-ci

**Comment by jo-fr** [comment]
We should also unify the usage of env variables and default values for them in the scraper. Because at the moment some scraper require a set env variable and others have a default value
