### ISSUE TITLE
Download instagram posts

### ISSUE THREAD

**Issue by alexmorten** [codeuniversity/smag-mvp#45]
Building on top of https://github.com/codeuniversity/smag-mvp/tree/temp/img-downloader 
- [x] filter the changestream of posts, for each created post or updated post where the url was changed, write download jobs for posts into new, partitioned topic
- [ ] read the download jobs topic in a new worker that 
  - [ ] download posts
  - [ ] puts images into s3
  - [ ]  writes path of image on s3 back into posts

**Comment by Urhengulas** [comment]
What posts?
