### ISSUE TITLE
Implement changestream filter for Twitter

### ISSUE THREAD

**Issue by Urhengulas** [codeuniversity/smag-mvp#47]
- [x] Implement in:
    - [x] twitter_inserter_users
    - [x] twitter_inserter_posts
- [x] Drop kafka.GetUserDiscoveryInserterConfig

**Comment by Urhengulas** [comment]
Depends on #40

**Comment by Urhengulas** [comment]
Drop kafka.GetUserDiscoveryInserterConfig

**Comment by m-lukas** [comment]
Test for filter?
