### ISSUE TITLE
Merge twitter scraper in mvp repo

### ISSUE THREAD

**Issue by m-lukas** [codeuniversity/smag-mvp#6]
TODO:
- [x] add twitter scraper to repo
- [x] add twitter scraper to docker-compose
- [x] add instagram scraper to docker-compose
- [x] refactor postgres-inserter with `gorm` package (https://github.com/jinzhu/gorm)
- [ ] refactor insertion functions to take input from both scrapers

**Comment by m-lukas** [comment]
Renamed `scraper` to `instagram_scraper`, `twitterscraper` to `twitter_scraper`

TODO:
- [ ] adapt documentation

**Comment by m-lukas** [comment]
What we did additionally:
- fix naming issues on docker build
- increase reconnect_backoff in twitter_scraper
- out-comment neo4j in docker-compose

**Comment by m-lukas** [comment]
Branch: `feature/implement-gorm`

- [x] replace all SQL queries in `postgres-inserter` to use `gorm` package
* [x] fix import issue in `instagram_scraper`

**Comment by Urhengulas** [comment]
What did we do today:
- [x] fix unessesary issues
  * dockerfile instascraper
  * dockerfile of instagram_postgres-inserter
- [x] add twitter_postgres-inserter package
- [x] add raw models for twitter users and posts

**Comment by Urhengulas** [comment]
What needs to be done:

- [ ] convert raw data models to cleaned version to be inserted into postgres
- [ ] have fun
